<?php 
    $brand = $this->getBrand();
    if($brand):
    if($brand->getId()):
?>
<div class="some_extra_icon">
<a href="<?php echo $this->getUrl($brand->getUrlKey());?>">
    <?php
        if($brand->getThumbnailImage())
		{
            //$path = 'brands' . DS . $brand->getId();
            $path = 'brands' . DS . 'thumbnail'.DS.$brand->getId();
            $imgSrc = Mage::helper('shopbybrand/image')->init($brand, $path)->resizeThumbnail(60, 40);
            ?>
                <img  src="<?php echo $imgSrc;?>" title="<?php echo $brand->getName();?>"/>
            <?php
		}
    ?>                                                                     
</a>
</div>

<?php endif; endif; ?>
