<form name="lightfinder" action="<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/" id="lightfinder" method="GET">
<h1 class="light_finder_title">Light Finder</h1>
<div id="main-lightfinder">
<div class="which_room lightfinder_inner">
<div class="lightfinder_inner_title">Which Room?</div>
<select>
 <option value="">Any Room</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<div class="which_type lightfinder_inner">
<div class="lightfinder_inner_title">Which Type? </div>

<select>
 <option value="">Any Type</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<div class="which_finish lightfinder_inner">
<div class="lightfinder_inner_title">Which Finish? </div>
<select>
 <option value="">Any Finish</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<div class="your_style lightfinder_inner">
<div class="lightfinder_inner_title">Your Style?</div>
<select>
 <option value="">Any Style</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<div class="your_budget lightfinder_inner">
<div class="lightfinder_inner_title">Your Budget? </div>
<select>
 <option value="">Any Budget</option>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
</div>
<div class="reset_submitlightfinder lightfinder_inner">
<input type="button" id="reset" value="reset" name="reset" />
</div>
<div class="submit_submitlightfinder">
<input type="submit" id="submitlightfinder" value="Submit" name="submitlightfinder" />
</div>
</div>
</form>