<div class="horizontal_rulefor_mob"></div>
<h1 class="light_finder_title">Light Finder</h1>
<div class="reset_submitlightfinder">
	<input type="button" id="reset" class="reset" value="" name="reset" />
</div>

<a class="show_hide_toggle magic_arrow_down" id="show_hide_toggle" href="javascript:void(0);" dataparam="main-lightfinder" >Show</a>
 
<div class="for_desktop_tab">
<div id="main-lightfinder-desktop">
	<form name="lightfinder" action="<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/" id="lightfinder" method="GET">
		<div class="which_room lightfinder_inner">
		<div class="lightfinder_inner_title">Which Room?</div>
		<select>
		 <option value="">Any Room</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="which_type lightfinder_inner">
		<div class="lightfinder_inner_title">Which Type? </div>

		<select>
		 <option value="">Any Type</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="which_finish lightfinder_inner">
		<div class="lightfinder_inner_title">Which Finish? </div>
		<select>
		 <option value="">Any Finish</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="your_style lightfinder_inner">
		<div class="lightfinder_inner_title">Your Style?</div>
		<select>
		 <option value="">Any Style</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="your_budget lightfinder_inner">
		<div class="lightfinder_inner_title">Your Budget? </div>
		<select>
		 <option value="">Any Budget</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>		
		<div class="submit_submitlightfinder">			
			<div class="submitlightfinder_1">
				<input type="submit" id="submitlightfinder" value="GO" name="submitlightfinder" />
			</div>
		</div>
	</form>
</div>
</div>
<div class="for_mobile">
<div id="main-lightfinder">
	<form name="lightfinder" action="<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/" id="lightfinder" method="GET">
		<div class="which_room lightfinder_inner">
		<div class="lightfinder_inner_title">Which Room?</div>
		<select>
		 <option value="">Any Room</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="which_type lightfinder_inner">
		<div class="lightfinder_inner_title">Which Type? </div>

		<select>
		 <option value="">Any Type</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="which_finish lightfinder_inner">
		<div class="lightfinder_inner_title">Which Finish? </div>
		<select>
		 <option value="">Any Finish</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="your_style lightfinder_inner">
		<div class="lightfinder_inner_title">Your Style?</div>
		<select>
		 <option value="">Any Style</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>
		<div class="your_budget lightfinder_inner">
		<div class="lightfinder_inner_title">Your Budget? </div>
		<select>
		 <option value="">Any Budget</option>
		  <option value="volvo">Volvo</option>
		  <option value="saab">Saab</option>
		  <option value="mercedes">Mercedes</option>
		  <option value="audi">Audi</option>
		</select>
		</div>		
		<div class="submit_submitlightfinder">
			<div class="reset_submitlightfinder_1">
				<input type="button" id="reset"  class="reset" value="" name="reset" />
			</div>
			<div class="submitlightfinder_1">
				<input type="submit" id="submitlightfinder" value="GO" name="submitlightfinder" />
			</div>
		</div>
	</form>
</div>
</div>
