<div class="horizontal_rulefor_mob"></div>
<h1 class="light_finder_title">Light Finder</h1>
<div class="reset_submitlightfinder">
	<input type="button" id="reset" class="reset" value="" name="reset" />
</div>
<a class="show_hide_toggle magic_arrow_down" id="show_hide_toggle" href="javascript:void(0);" dataparam="main-lightfinder" >Show</a>
 
<div class="for_desktop_tab">
<div id="main-lightfinder-desktop">
	<form name="lightfinder" action="<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/" id="lightfinder" method="GET">
	<?php 
 		/*foreach ($this->getSearchableAttributes() as $_attribute): 
 			$_code = $_attribute->getAttributeCode();
 			if($this->getAttributeInputType($_attribute)=='select'){
 				if($_code=='room'){
 					echo $_code;
 				}
 				if(){ room  type_of_bulbs  finish  style

 				}
 			}*/
 			$roomArray=array();
 			$typeArray=array();
 			$finishArray=array();
 			$styleArray=array();
 			//load room values in value label format
 			$attributeIdRoom = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','room');
 			$collectionRoom =Mage::getResourceModel('eav/entity_attribute_option_collection')
                ->setPositionOrder('asc')
                ->setAttributeFilter($attributeIdRoom)
                ->setStoreFilter(Mage::app()->getStore()->getId())
                ->load();
            $roomArray=$collectionRoom->toOptionArray();
            //End of room values 
             //load Type values in value label format
 			$attributeIdType = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','type_of_bulbs');
 			$collectionType =Mage::getResourceModel('eav/entity_attribute_option_collection')
                ->setPositionOrder('asc')
                ->setAttributeFilter($attributeIdType)
                ->setStoreFilter(Mage::app()->getStore()->getId())
                ->load();
            $typeArray=$collectionType->toOptionArray();
            //End of Type values 
             //load Finish values in value label format
 			$attributeIdFinish = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','finish');
 			$collectionFinish =Mage::getResourceModel('eav/entity_attribute_option_collection')
                ->setPositionOrder('asc')
                ->setAttributeFilter($attributeIdFinish)
                ->setStoreFilter(Mage::app()->getStore()->getId())
                ->load();
            $finishArray=$collectionFinish->toOptionArray();
            //End of Finish values 
             //load style values in value label format
 			$attributeIdStyle = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product','style');
 			$collectionStyle =Mage::getResourceModel('eav/entity_attribute_option_collection')
                ->setPositionOrder('asc')
                ->setAttributeFilter($attributeIdStyle)
                ->setStoreFilter(Mage::app()->getStore()->getId())
                ->load();
            $styleArray=$collectionStyle->toOptionArray();
            //End of style values 

          

         //       exit;

 	?>
		<div class="which_room lightfinder_inner">
		<div class="lightfinder_inner_title">Which Room?</div>
		<select id="room" name="room[]" >
		 <option value="">Any Room</option>
		 <?php foreach ($roomArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="which_type lightfinder_inner">
		<div class="lightfinder_inner_title">Which Type? </div>

		<select id="type" name="type_of_bulbs[]">
		 <option value="">Any Type</option>
		  <?php foreach ($typeArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="which_finish lightfinder_inner">
		<div class="lightfinder_inner_title">Which Finish? </div>
		<select id="finish" name="finish[]">
		 <option value="">Any Finish</option>
		  <?php foreach ($finishArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="your_style lightfinder_inner">
		<div class="lightfinder_inner_title">Your Style?</div>
		<select id="style" name="style[]">
		 <option value="">Any Style</option>
		  <?php foreach ($styleArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="your_budget lightfinder_inner">
		<div class="lightfinder_inner_title">Your Budget?</div>
		<select id="budget" >
		 <option value="">Any Budget</option>
		  <option value=">0-1000">$0-$1000</option>
		  <option value="1000-2000">$1000-$2000</option>
		  <option value="2000-3000">$2000-$3000</option>
		  <option value="3000-10000">$3000-$10000</option>
		</select>
		</div>		
		<div class="submit_submitlightfinder">			
			<div class="submitlightfinder_1">
				<input type="button" onclick="sumitlightfinder('<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/');" id="submitlightfinder" value="GO" name="submitlightfinder" />
			</div>
		</div>
	</form>
</div>
</div>
<div class="for_mobile">
<div id="main-lightfinder">
	<form name="lightfinder" action="<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/" id="lightfinder" method="GET">
		<div class="which_room lightfinder_inner">
		<div class="lightfinder_inner_title">Which Room?</div>
		<select id="room-mobile" name="room[]" >
		 <option value="">Any Room</option>
		 <?php foreach ($roomArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="which_type lightfinder_inner">
		<div class="lightfinder_inner_title">Which Type? </div>

		<select id="type-mobile" name="type_of_bulbs[]">
		 <option value="">Any Type</option>
		  <?php foreach ($typeArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="which_finish lightfinder_inner">
		<div class="lightfinder_inner_title">Which Finish? </div>
		<select id="finish-mobile" name="finish[]">
		 <option value="">Any Finish</option>
		  <?php foreach ($finishArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="your_style lightfinder_inner">
		<div class="lightfinder_inner_title">Your Style?</div>
		<select id="style-mobile" name="style[]">
		 <option value="">Any Style</option>
		  <?php foreach ($styleArray as $key) { ?>
		  <option value="<?php echo $key['value']; ?>"><?php echo $key['label']; ?></option>
		 <?php } ?>
		</select>
		</div>
		<div class="your_budget lightfinder_inner">
		<div class="lightfinder_inner_title">Your Budget? </div>
		<select id="budget-mobile" >
		 <option value="">Any Budget</option>
		  <option value=">0-1000">$0-$1000</option>
		  <option value="1000-2000">$1000-$2000</option>
		  <option value="2000-3000">$2000-$3000</option>
		  <option value="3000-10000">$3000-$10000</option>
		</select>
		</div>		
		<div class="submit_submitlightfinder">
			<div class="reset_submitlightfinder_1">
				<input type="button" id="reset"  class="reset" value="" name="reset" />
			</div>
			<div class="submitlightfinder_1">
				<input type="button" onclick="sumitlightfinderMobile('<?php echo $this->getBaseUrl()?>catalogsearch/advanced/result/');" id="submitlightfinder" value="GO" name="submitlightfinder" />
			</div>
		</div>
	</form>
</div>
</div>

