<div class="slide-container">
    <div class="home-slide flexslider" id="homeSlider">
        <ul class="slides" id="slides">
            <?php
            $slideIndex = 0;
            foreach ($this->getSlides() as $slide):
                $slideIndex ++;
            ?>
            <li class="slide" data-cap="<?php echo $slide->getName(); ?>">					
                   <a href="<?php echo $slide->getLink(); ?>">
				   		<div class="banner_content_inner">
						<?php echo $slide->getCaption(); ?>	
						</div>
				   		<img src='<?php echo $slide->getImage(); ?>' />
				   </a>
			</li>
            <?php endforeach; ?>
        </ul>
    </div>
</div><!--// End slide container -->
<div class="clearer"></div>
