<?php
/* @var $this AW_Twitter_Connect_Block_Abstract */
// WARNING! Don't change span class "twitterconnect-button"
?>
<div id="twitterconnect_wrapper" style="display: none;">
    <span class="twitterconnect-button">
    <?php if(strtolower(substr($this->getLinkUrl(),0,4))==='http'): ?>
        <a href="<?php echo $this->getLinkUrl(); ?>" title="<?php echo $this->getTitle(); ?>" class="link-twitter">
    <?php elseif($this->getLinkUrl()): ?>
        <a href="<?php echo $this->getUrl($this->getLinkUrl()); ?>" title="<?php echo $this->getTitle(); ?>" class="link-twitter">
    <?php endif; ?>
            <span><?php echo $this->getTitle(); ?></span>
    <?php if($this->getLinkUrl()): ?>
        </a>
    <?php endif ?>
    </span>
</div>