<?php 
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $_category->getImageUrl()) {
	$_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
	$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
} ?>

<?php if ($_imgUrl) : ?>
	<?php echo $_imgHtml; ?>
<?php else : ?>
	<div class="page-title category-title">
		<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	</div>
<?php endif; ?>
