<?php 
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_category->getTextOverlay();
$_imgHtml   = '';

if ($_imgUrl = $_category->getImageUrl()) {
	$_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
	$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
} ?>
<?php 
$attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_category', 'text_overlay');
 $text = $attribute->getSource()->getOptionText($_category->getTextOverlay());

 $overlayContentattribute = Mage::getSingleton('eav/config')->getAttribute('catalog_category', 'overlay_content');
 $overlayContent = $attribute->getSource()->getOptionText($_category->getOverlayContent());
?>


<?php if ($_imgUrl) : ?>
		<?php if($text=='Left'){
			?>
			<div class="left_over">
			<div class="left_over_title"><?php echo $catName=$_helper->categoryAttribute($_category, $_category->getName(), 'name');?></div>
			<div class="left_over_desc">
				<?php //echo $description=$_category->getDescription();?>
				<?php echo $overlayContent; ?>
			</div>
			</div>
			<?php 
			echo $_imgHtml; 
		}elseif($text=='Right'){
			?>
			<div class="right_over">
			<div class="right_over_title"><?php echo $catName=$_helper->categoryAttribute($_category, $_category->getName(), 'name');?></div>
			<div class="right_over_desc">
				<?php //echo $description=$_category->getDescription();?>
				<?php echo $overlayContent; ?>
			</div>
			</div>
			<?php 
			echo $_imgHtml; 
		}else{
			?>
			<div class="none">
			</div>
			<?php 
			 echo $_imgHtml; 
		} ?>
	
<?php else : ?>
	<div class="page-title category-title">
		<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	</div>
<?php endif; ?>
