<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Affiliate
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<div class="dashboard">
    <h2 class="sub-title"><?php echo $this->__("Create new report"); ?></h2>

    <div class="info-box">
        <div class="box-content">
            <form id="create-report-form" method="post" action="<?php echo $this->getActionUrl();?>">
                <div class="col2-set">
                    <div class="col-1">
                        <div class="form-list awreport">
                            <div class="fields">
                                <div id="report-type-container" class="field">
                                    <?php echo $this->getReportTypeField(); ?>
                                </div>
                                <div id="date-period-container" class="field">
                                    <?php echo $this->getReportDatePeriodField(); ?>
                                </div>
                                <div id="date-periodicity-container" class="field">
                                    <div id="period-from-container">
                                        <?php echo $this->getPeriodFromField();?>
                                        <script type="text/javascript">
                                            //fix magento calendar bug in always time displaying
                                            calendarSetupObject.showsTime = false;
                                            Calendar.setup(calendarSetupObject);
                                        </script>
                                    </div>
                                    <div id="period-to-container">
                                        <?php echo $this->getPeriodToField();?>
                                        <script type="text/javascript">
                                            //fix magento calendar bug in always time displaying
                                            calendarSetupObject.showsTime = false;
                                            Calendar.setup(calendarSetupObject);
                                        </script>
                                    </div>
                                </div>
                                <div id="detalization-container" class="field">
                                    <?php echo $this->getDetalizationsField();?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="form-list awreport">
                            <div class="fields">
                                <div class="field awcampaigns">
                                    <?php echo $this->getCampaignsField();?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>


<div class="button-set">
    <button class="button" id="create-report-btn">
        <span><span><?php echo $this->__('Create Report'); ?></span></span>
    </button>
</div>
<script type="text/javascript">
    var config = {
        formSpecified: <?php echo $this->isFormSpecified() ? 'true' : 'false';?>,
        msg:{
            reportCreating:'<?php echo $this->__('Report creating...');?>',
            campaignNotSelected:'<?php echo $this->__('You must select at least one campaign');?>'
        }
    };
    AWReportForm.initialize(config);
</script>
</div>