<?php
$installer = $this;

$installer->startSetup();


/* Add attribute group to attribute set */
$productAttributesInfo =
array(
    'finish' => array (
          'group'                      => 'Product Options',
          'type'                       => 'int',
          'label'                      => 'Finish',
          'input'                      => 'select',
          'required'                   => '0',
          'user_defined'               => '1',
          'global'                     => '1',
          'visible'                    => '1',
          'searchable'                 => '1',
          'filterable'                 => '1',
          'comparable'                 => '1',
          'visible_on_front'           => '1',
          'is_html_allowed_on_front'   => '1',
          'filterable_in_search'       => '1',
          'used_in_product_listing'    => '1',
          'is_configurable'            => '0',
          'apply_to'                   => 'simple,configurable',
          'visible_in_advanced_search' => '1',
          'position'                   => '1',
          'used_for_promo_rules'       => '1',
          'option'                     => array (
                                          'values' => array (
                                              0 => 'Brass',
                                              1 => 'Black',
                                              2 => 'Bronze',
                                              3 => 'Silver',
                                              4 => 'Chrome',
                                              5 => 'Brown',
                                              6 => 'Copper',
                                              7 => 'Iron',
                                              8 => 'Pewter',
                                              9 => 'Rust'
                                            ),
                                          ),
    ),
	'special_features' => array (
	  'group'                      => 'Product Options',
	  'type'                       => 'int',
	  'label'                      => 'Special Features',
	  'input'                      => 'select',
	  'required'                   => '0',
	  'user_defined'               => '1',
	  'global'                     => '1',
	  'visible'                    => '1',
	  'searchable'                 => '1',
	  'filterable'                 => '1',
	  'comparable'                 => '1',
	  'visible_on_front'           => '1',
	  'is_html_allowed_on_front'   => '1',
	  'filterable_in_search'       => '1',
	  'used_in_product_listing'    => '1',
	  'is_configurable'            => '0',
	  'apply_to'                   => 'simple,configurable',
	  'visible_in_advanced_search' => '1',
	  'position'                   => '1',
	  'used_for_promo_rules'       => '1',
	  'option'                     => array (
									  'values' => array (
										  0 => 'New',
										  1 => 'Clearance',
										  2 => 'Energy Star',
										  3 => 'ADA',
										  4 => 'In Stores'
										),
									  ),
    ),
	'type_of_bulbs' => array (
	  'group'                      => 'Product Options',
	  'type'                       => 'int',
	  'label'                      => 'Type of bulbs',
	  'input'                      => 'select',
	  'required'                   => '0',
	  'user_defined'               => '1',
	  'global'                     => '1',
	  'visible'                    => '1',
	  'searchable'                 => '1',
	  'filterable'                 => '1',
	  'comparable'                 => '1',
	  'visible_on_front'           => '1',
	  'is_html_allowed_on_front'   => '1',
	  'filterable_in_search'       => '1',
	  'used_in_product_listing'    => '1',
	  'is_configurable'            => '0',
	  'apply_to'                   => 'simple,configurable',
	  'visible_in_advanced_search' => '1',
	  'position'                   => '1',
	  'used_for_promo_rules'       => '1',
	  'option'                     => array (
									 'values' => array (
											  0 => 'Compact',
											  1 => 'Fluorescent',
											  2 => 'Candelabra',
											  3 => 'Halogen',
											  4 => 'LED',
											  5 => 'Incandescent',
											  6 => 'Xenon',
											  7 => 'Fluorescent',
											  8 => 'Medium',
											  9 => 'CFL',
											  10 => 'Krypton',
											  11 => 'C-G16.5',
											  12 => 'Medum Base Incandescent',
											  13 => 'Medum Base Incandescent19',
											  14 => 'Standard Medium Base',
											  15 => 'Bi-Pin GU24 CFL'											  
                                            ),
									  ),
    ),
	'height' => array (
	  'group'                      => 'Product Options',
	  'type'                       => 'varchar',
	  'label'                      => 'Height',
	  'input'                      => 'text',
	  'required'                   => '0',
	  'user_defined'               => '1',
	  'global'                     => '1',
	  'visible'                    => '1',
	  'searchable'                 => '1',
	  'filterable'                 => '1',
	  'comparable'                 => '1',
	  'visible_on_front'           => '1',
	  'is_html_allowed_on_front'   => '1',
	  'filterable_in_search'       => '1',
	  'used_in_product_listing'    => '1',
	  'is_configurable'            => '0',
	  'apply_to'                   => 'simple,configurable',
	  'visible_in_advanced_search' => '1',
	  'position'                   => '1',
	  'used_for_promo_rules'       => '1' 
    ),
	'width' => array (
	  'group'                      => 'Product Options',
	  'type'                       => 'varchar',
	  'label'                      => 'Width',
	  'input'                      => 'text',
	  'required'                   => '0',
	  'user_defined'               => '1',
	  'global'                     => '1',
	  'visible'                    => '1',
	  'searchable'                 => '1',
	  'filterable'                 => '1',
	  'comparable'                 => '1',
	  'visible_on_front'           => '1',
	  'is_html_allowed_on_front'   => '1',
	  'filterable_in_search'       => '1',
	  'used_in_product_listing'    => '1',
	  'is_configurable'            => '0',
	  'apply_to'                   => 'simple,configurable',
	  'visible_in_advanced_search' => '1',
	  'position'                   => '1',
	  'used_for_promo_rules'       => '1' 
    )
   /* 'brands' => array (
        'group'                      => 'General',
        'type'                       => 'int',
        'label'                      => 'Brands',
        'input'                      => 'select',
        'required'                   => '0',
        'user_defined'               => '1',
        'global'                     => '1',
        'visible'                    => '1',
        'searchable'                 => '1',
        'filterable'                 => '1',
        'comparable'                 => '1',
        'visible_on_front'           => '1',
        'is_html_allowed_on_front'   => '1',
        'filterable_in_search'       => '1',
        'used_in_product_listing'    => '1',
        'is_configurable'            => '1',
        'apply_to'                   => 'simple',
        'visible_in_advanced_search' => '1',
        'position'                   => '1',
        'used_for_promo_rules'       => '1',
        'option'                     => array (
                'values' => array (
                        0 => 'Adidas',
                        1 => 'Anvil',
                        2 => 'Ashworth',
                        3 => 'Columbia',
                        4 => 'Eddie Bauer',
                        5 => 'Fossil',
                        6 => 'Guess',
                        7 => 'Hanes',
                        8 => 'Jarzees',
                        9 => 'Nike'
                ),
        ),
	)*/
    
);

foreach ($productAttributesInfo as $attributeCode => $attributeParams) {
    $installer->addAttribute(Mage_Catalog_Model_Product::ENTITY, $attributeCode, $attributeParams);
}

$installer->endSetup();