<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Affiliate
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Affiliate
 * @copyright  Copyright (c) 2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @var $this AW_Affiliate_Block_Customer_Topinfo
 */
?>
<div class="dashboard">
    <div class="col2-set">
        <div class="col-1">
            <?php echo $this->getChildHtml('awaffiliate_customer_account_summary');?>
        </div>
        <div class="col-2">
            <?php echo $this->getChildHtml('awaffiliate_customer_account_report');?>
        </div>
    </div>
</div>
<?php if ($campaignDescription = $this->getCurrentCampaignDescription()) : ?>
<h2 class="sub-title"><?php echo $this->__('Description'); ?></h2>
<div class="info-box fieldset">
    <div class="row"><?php echo $campaignDescription ?></div>
</div>
<?php endif ?>
