<div class="page-title">
    <h1><?php echo $this->__('Google Connect') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php echo $this->getChildHtml('googleconnect_form_before') ?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Google Post') ?></h2>
        <ul class="form-list">
            <li class="control">
                <input type="checkbox" name="google_post" id="google_post" value="1"
                       title="<?php echo $this->__('Post order details to Google'); ?>"<?php if ($this->getIsPostToGoogle()): ?> checked="checked"<?php endif; ?>
                       class="checkbox"/>
                <label for="google_post"><?php echo $this->__('Post order details to Google') ?></label>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button">
            <span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>