<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Onestepcheckout
 * @version    1.3.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div id="aw-onestepcheckout-title">
    <h1><?php echo $this->getTitle();?></h1>
     <?php if(!$this->isCustomerLoggedIn()): ?>
    <p id="aw-onestepcheckout-title-description"><?php //echo $this->getDescription();?> Already registered? <a href="javascript:void(0);"  id="login-chkout">Login here</a></p>
     <?php endif; ?>
</div>
<script type="text/javascript">
   jQuery("#login-chkout").click(function(){
    jQuery("#aw-onestepcheckout-authentification").toggle();
});
</script>