<?php
/* @var $this AW_Facebook_Connect_Block_Abstract*/
// WARNING! Don't change span class "facebookconnect-button"
?>
<div id="facebookconnect_wrapper" style="display: none;">
    <span class="facebookconnect-button">
    <?php if(strtolower(substr($this->getLinkUrl(),0,4))==='http'): ?>
        <a href="<?php echo $this->getLinkUrl(); ?>" title="<?php echo $this->getTitle(); ?>" class="link-facebook">
    <?php elseif($this->getLinkUrl()): ?>
        <a href="<?php echo $this->getUrl($this->getLinkUrl()); ?>" title="<?php echo $this->getTitle(); ?>" class="link-facebook">
    <?php endif; ?>
            <span><?php echo $this->getTitle(); ?></span>
    <?php if($this->getLinkUrl()): ?>
        </a>
    <?php endif ?>
    </span>
</div>